#!/bin/bash 

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

source CONFIG

case "$1" in 
	-i)
		if [ $# -ne 3 ]; then
			echo Usage: atsumi-go -i namespace name
			exit 1
		fi;
		echo Getting latest project...
		git clone git://github.com/phoenixrises/atsumi-project-base.git bootstrap
		cd bootstrap
		files=`git ls-files`
		# Must be a better way of doing this
		find -name '.git' -type d -print | xargs rm -rf {}
		echo Updating namespaces...
		for file in $files
		do
			if ( grep -q 'boot_' $file ); then
				`sed -i s/boot_/$2_/g $file`
				echo -ne .
			fi;
			if ( echo $file | grep -qi 'boot_'); then
				newfile=`echo $file | sed s/boot_/$2_/g`
				mv $file $newfile
				echo -ne .
			fi;
		done
		echo .
		echo Updating index.php for new folder
		sed -i s/bootstrap/$3/g index.php
		echo Changing permissions for web access...
		cd ../
		chgrp -R www-data bootstrap/
		chmod -R g+r bootstrap/
		chmod -R g+w bootstrap/log
		echo Moving project to new location
		mv bootstrap/ $project_dir/$3

		echo Complete!
		;;
esac;
