#!/usr/bin/php
<?php
require_once("../atsumi/init.php");
atsumi_Loader::references(array(
	'atsumi'	=> 'helpers mvc database',
	'atsumi-go'	=> 'app mvc'
));

$settings = new ago_Settings();

Atsumi::initApp($settings);
// Debug is useless on CLI
atsumi_Debug::setActive(false);

try {
	Atsumi::app__go($argv);
} catch(Exception $e) {
	echo "An exception occured";
	var_dump($e);
}
echo "\n";
?>
